// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/tc.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//分支事务状态
type LocalTransactionStatus int32

const (
	LocalTransactionStatus_UNKNOW     LocalTransactionStatus = 0
	LocalTransactionStatus_COMMITED   LocalTransactionStatus = 1
	LocalTransactionStatus_ROLLBACKED LocalTransactionStatus = 2
)

var LocalTransactionStatus_name = map[int32]string{
	0: "UNKNOW",
	1: "COMMITED",
	2: "ROLLBACKED",
}

var LocalTransactionStatus_value = map[string]int32{
	"UNKNOW":     0,
	"COMMITED":   1,
	"ROLLBACKED": 2,
}

func (x LocalTransactionStatus) String() string {
	return proto.EnumName(LocalTransactionStatus_name, int32(x))
}

func (LocalTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{0}
}

//start，业务方调用，注册全局tid，并标记该service为此事务的发起者，全部为同步请求情况下，可以省略该步骤，tid由子业务自己生成。
type StartRequest struct {
	RequestPath          *Path    `protobuf:"bytes,1,opt,name=requestPath,proto3" json:"requestPath,omitempty"`
	TraceId              string   `protobuf:"bytes,2,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{0}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetRequestPath() *Path {
	if m != nil {
		return m.RequestPath
	}
	return nil
}

func (m *StartRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type StartReply struct {
	ReplyInfo            *ReplyInfo `protobuf:"bytes,1,opt,name=replyInfo,proto3" json:"replyInfo,omitempty"`
	Tid                  string     `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	TraceId              string     `protobuf:"bytes,3,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StartReply) Reset()         { *m = StartReply{} }
func (m *StartReply) String() string { return proto.CompactTextString(m) }
func (*StartReply) ProtoMessage()    {}
func (*StartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{1}
}

func (m *StartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReply.Unmarshal(m, b)
}
func (m *StartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReply.Marshal(b, m, deterministic)
}
func (m *StartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReply.Merge(m, src)
}
func (m *StartReply) XXX_Size() int {
	return xxx_messageInfo_StartReply.Size(m)
}
func (m *StartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartReply proto.InternalMessageInfo

func (m *StartReply) GetReplyInfo() *ReplyInfo {
	if m != nil {
		return m.ReplyInfo
	}
	return nil
}

func (m *StartReply) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *StartReply) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

//globalCommit，业务方调用，全局提交，只有此事务的发起者才可以发起该请求。
type GlobalCommitRequest struct {
	RequestPath          *Path    `protobuf:"bytes,1,opt,name=requestPath,proto3" json:"requestPath,omitempty"`
	Tid                  string   `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	LockKey              string   `protobuf:"bytes,3,opt,name=lockKey,proto3" json:"lockKey,omitempty"`
	TraceId              string   `protobuf:"bytes,4,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalCommitRequest) Reset()         { *m = GlobalCommitRequest{} }
func (m *GlobalCommitRequest) String() string { return proto.CompactTextString(m) }
func (*GlobalCommitRequest) ProtoMessage()    {}
func (*GlobalCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{2}
}

func (m *GlobalCommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalCommitRequest.Unmarshal(m, b)
}
func (m *GlobalCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalCommitRequest.Marshal(b, m, deterministic)
}
func (m *GlobalCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalCommitRequest.Merge(m, src)
}
func (m *GlobalCommitRequest) XXX_Size() int {
	return xxx_messageInfo_GlobalCommitRequest.Size(m)
}
func (m *GlobalCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalCommitRequest proto.InternalMessageInfo

func (m *GlobalCommitRequest) GetRequestPath() *Path {
	if m != nil {
		return m.RequestPath
	}
	return nil
}

func (m *GlobalCommitRequest) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *GlobalCommitRequest) GetLockKey() string {
	if m != nil {
		return m.LockKey
	}
	return ""
}

func (m *GlobalCommitRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type GlobalCommitReply struct {
	ReplyInfo            *ReplyInfo `protobuf:"bytes,1,opt,name=replyInfo,proto3" json:"replyInfo,omitempty"`
	TraceId              string     `protobuf:"bytes,2,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GlobalCommitReply) Reset()         { *m = GlobalCommitReply{} }
func (m *GlobalCommitReply) String() string { return proto.CompactTextString(m) }
func (*GlobalCommitReply) ProtoMessage()    {}
func (*GlobalCommitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{3}
}

func (m *GlobalCommitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalCommitReply.Unmarshal(m, b)
}
func (m *GlobalCommitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalCommitReply.Marshal(b, m, deterministic)
}
func (m *GlobalCommitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalCommitReply.Merge(m, src)
}
func (m *GlobalCommitReply) XXX_Size() int {
	return xxx_messageInfo_GlobalCommitReply.Size(m)
}
func (m *GlobalCommitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalCommitReply.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalCommitReply proto.InternalMessageInfo

func (m *GlobalCommitReply) GetReplyInfo() *ReplyInfo {
	if m != nil {
		return m.ReplyInfo
	}
	return nil
}

func (m *GlobalCommitReply) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

//globalRollback，业务方调用，全局回滚，只有此事务的发起者才可以发起该请求。
type GlobalRollbackRequest struct {
	RequestPath          *Path    `protobuf:"bytes,1,opt,name=requestPath,proto3" json:"requestPath,omitempty"`
	Tid                  string   `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	TraceId              string   `protobuf:"bytes,3,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalRollbackRequest) Reset()         { *m = GlobalRollbackRequest{} }
func (m *GlobalRollbackRequest) String() string { return proto.CompactTextString(m) }
func (*GlobalRollbackRequest) ProtoMessage()    {}
func (*GlobalRollbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{4}
}

func (m *GlobalRollbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalRollbackRequest.Unmarshal(m, b)
}
func (m *GlobalRollbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalRollbackRequest.Marshal(b, m, deterministic)
}
func (m *GlobalRollbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalRollbackRequest.Merge(m, src)
}
func (m *GlobalRollbackRequest) XXX_Size() int {
	return xxx_messageInfo_GlobalRollbackRequest.Size(m)
}
func (m *GlobalRollbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalRollbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalRollbackRequest proto.InternalMessageInfo

func (m *GlobalRollbackRequest) GetRequestPath() *Path {
	if m != nil {
		return m.RequestPath
	}
	return nil
}

func (m *GlobalRollbackRequest) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *GlobalRollbackRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type GlobalRollbackReply struct {
	ReplyInfo            *ReplyInfo `protobuf:"bytes,1,opt,name=replyInfo,proto3" json:"replyInfo,omitempty"`
	TraceId              string     `protobuf:"bytes,2,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GlobalRollbackReply) Reset()         { *m = GlobalRollbackReply{} }
func (m *GlobalRollbackReply) String() string { return proto.CompactTextString(m) }
func (*GlobalRollbackReply) ProtoMessage()    {}
func (*GlobalRollbackReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{5}
}

func (m *GlobalRollbackReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalRollbackReply.Unmarshal(m, b)
}
func (m *GlobalRollbackReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalRollbackReply.Marshal(b, m, deterministic)
}
func (m *GlobalRollbackReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalRollbackReply.Merge(m, src)
}
func (m *GlobalRollbackReply) XXX_Size() int {
	return xxx_messageInfo_GlobalRollbackReply.Size(m)
}
func (m *GlobalRollbackReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalRollbackReply.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalRollbackReply proto.InternalMessageInfo

func (m *GlobalRollbackReply) GetReplyInfo() *ReplyInfo {
	if m != nil {
		return m.ReplyInfo
	}
	return nil
}

func (m *GlobalRollbackReply) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

//锁结构，所有字段均是为了保证锁的唯一性，不污染其他情况下数据，因此其中的库与连接实际上只是一个标记而已。
type Lock struct {
	PrimaryK             string   `protobuf:"bytes,1,opt,name=primaryK,proto3" json:"primaryK,omitempty"`
	PrimaryV             string   `protobuf:"bytes,2,opt,name=primaryV,proto3" json:"primaryV,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Connection           string   `protobuf:"bytes,5,opt,name=connection,proto3" json:"connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lock) Reset()         { *m = Lock{} }
func (m *Lock) String() string { return proto.CompactTextString(m) }
func (*Lock) ProtoMessage()    {}
func (*Lock) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{6}
}

func (m *Lock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lock.Unmarshal(m, b)
}
func (m *Lock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lock.Marshal(b, m, deterministic)
}
func (m *Lock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lock.Merge(m, src)
}
func (m *Lock) XXX_Size() int {
	return xxx_messageInfo_Lock.Size(m)
}
func (m *Lock) XXX_DiscardUnknown() {
	xxx_messageInfo_Lock.DiscardUnknown(m)
}

var xxx_messageInfo_Lock proto.InternalMessageInfo

func (m *Lock) GetPrimaryK() string {
	if m != nil {
		return m.PrimaryK
	}
	return ""
}

func (m *Lock) GetPrimaryV() string {
	if m != nil {
		return m.PrimaryV
	}
	return ""
}

func (m *Lock) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Lock) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Lock) GetConnection() string {
	if m != nil {
		return m.Connection
	}
	return ""
}

//register，RM或TM调用，调用时机为commit之前，请求锁成功后本地commit。注册分支事务，提交需锁的内容，尝试上锁。
type RegisterRequest struct {
	RequestPath          *Path    `protobuf:"bytes,1,opt,name=requestPath,proto3" json:"requestPath,omitempty"`
	Tid                  string   `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Locks                []*Lock  `protobuf:"bytes,3,rep,name=locks,proto3" json:"locks,omitempty"`
	TraceId              string   `protobuf:"bytes,4,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{7}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetRequestPath() *Path {
	if m != nil {
		return m.RequestPath
	}
	return nil
}

func (m *RegisterRequest) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *RegisterRequest) GetLocks() []*Lock {
	if m != nil {
		return m.Locks
	}
	return nil
}

func (m *RegisterRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type RegisterReply struct {
	ReplyInfo            *ReplyInfo `protobuf:"bytes,1,opt,name=replyInfo,proto3" json:"replyInfo,omitempty"`
	Lock                 bool       `protobuf:"varint,2,opt,name=lock,proto3" json:"lock,omitempty"`
	Ltid                 string     `protobuf:"bytes,3,opt,name=ltid,proto3" json:"ltid,omitempty"`
	TraceId              string     `protobuf:"bytes,4,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{8}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetReplyInfo() *ReplyInfo {
	if m != nil {
		return m.ReplyInfo
	}
	return nil
}

func (m *RegisterReply) GetLock() bool {
	if m != nil {
		return m.Lock
	}
	return false
}

func (m *RegisterReply) GetLtid() string {
	if m != nil {
		return m.Ltid
	}
	return ""
}

func (m *RegisterReply) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

//report，RM或TM调用，调用时机为commit/rollback之后。报告分支支付状态
type ReportRequest struct {
	RequestPath          *Path                  `protobuf:"bytes,1,opt,name=requestPath,proto3" json:"requestPath,omitempty"`
	Tid                  string                 `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Ltid                 string                 `protobuf:"bytes,3,opt,name=ltid,proto3" json:"ltid,omitempty"`
	Status               LocalTransactionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=proto.LocalTransactionStatus" json:"status,omitempty"`
	TraceId              string                 `protobuf:"bytes,5,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{9}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetRequestPath() *Path {
	if m != nil {
		return m.RequestPath
	}
	return nil
}

func (m *ReportRequest) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *ReportRequest) GetLtid() string {
	if m != nil {
		return m.Ltid
	}
	return ""
}

func (m *ReportRequest) GetStatus() LocalTransactionStatus {
	if m != nil {
		return m.Status
	}
	return LocalTransactionStatus_UNKNOW
}

func (m *ReportRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type ReportReply struct {
	ReplyInfo            *ReplyInfo `protobuf:"bytes,1,opt,name=replyInfo,proto3" json:"replyInfo,omitempty"`
	TraceId              string     `protobuf:"bytes,2,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReportReply) Reset()         { *m = ReportReply{} }
func (m *ReportReply) String() string { return proto.CompactTextString(m) }
func (*ReportReply) ProtoMessage()    {}
func (*ReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84212f77cd53b20b, []int{10}
}

func (m *ReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportReply.Unmarshal(m, b)
}
func (m *ReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportReply.Marshal(b, m, deterministic)
}
func (m *ReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportReply.Merge(m, src)
}
func (m *ReportReply) XXX_Size() int {
	return xxx_messageInfo_ReportReply.Size(m)
}
func (m *ReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReportReply proto.InternalMessageInfo

func (m *ReportReply) GetReplyInfo() *ReplyInfo {
	if m != nil {
		return m.ReplyInfo
	}
	return nil
}

func (m *ReportReply) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.LocalTransactionStatus", LocalTransactionStatus_name, LocalTransactionStatus_value)
	proto.RegisterType((*StartRequest)(nil), "proto.StartRequest")
	proto.RegisterType((*StartReply)(nil), "proto.StartReply")
	proto.RegisterType((*GlobalCommitRequest)(nil), "proto.GlobalCommitRequest")
	proto.RegisterType((*GlobalCommitReply)(nil), "proto.GlobalCommitReply")
	proto.RegisterType((*GlobalRollbackRequest)(nil), "proto.GlobalRollbackRequest")
	proto.RegisterType((*GlobalRollbackReply)(nil), "proto.GlobalRollbackReply")
	proto.RegisterType((*Lock)(nil), "proto.Lock")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "proto.RegisterReply")
	proto.RegisterType((*ReportRequest)(nil), "proto.ReportRequest")
	proto.RegisterType((*ReportReply)(nil), "proto.ReportReply")
}

func init() { proto.RegisterFile("pb/tc.proto", fileDescriptor_84212f77cd53b20b) }

var fileDescriptor_84212f77cd53b20b = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xf1, 0xda, 0x94, 0xf6, 0x65, 0x6c, 0xc1, 0xfc, 0x50, 0x34, 0x09, 0x54, 0x7a, 0x9a,
	0x90, 0xe8, 0xa4, 0x21, 0xfe, 0x00, 0xd6, 0x4d, 0xa8, 0x6a, 0xb7, 0x22, 0x6f, 0xd0, 0x13, 0x42,
	0x8e, 0x67, 0x58, 0x54, 0x27, 0x0e, 0x8e, 0x77, 0xe8, 0x91, 0x2b, 0x17, 0xf8, 0x67, 0xf8, 0xff,
	0x26, 0x3b, 0x4e, 0x9b, 0x48, 0xdd, 0x0e, 0x55, 0x4e, 0x79, 0xbf, 0xfc, 0xbe, 0x9f, 0xf7, 0xec,
	0x80, 0x9f, 0x45, 0x47, 0x9a, 0x0d, 0x33, 0x25, 0xb5, 0xc4, 0x9e, 0xfd, 0x1c, 0xec, 0x67, 0xd1,
	0x11, 0x93, 0x49, 0x22, 0xd3, 0x22, 0x3e, 0x98, 0xc3, 0xee, 0xa5, 0xa6, 0x4a, 0x13, 0xfe, 0xeb,
	0x96, 0xe7, 0x1a, 0xbf, 0x03, 0x5f, 0x15, 0xe6, 0x67, 0xaa, 0x6f, 0x42, 0xd4, 0x47, 0x87, 0xfe,
	0xb1, 0x5f, 0x14, 0x0f, 0x4d, 0x88, 0x54, 0xf3, 0x38, 0x84, 0xc7, 0x5a, 0x51, 0xc6, 0xc7, 0xd7,
	0xe1, 0x4e, 0x1f, 0x1d, 0xf6, 0x48, 0xe9, 0x0e, 0x6e, 0x00, 0x5c, 0xe3, 0x4c, 0x2c, 0xf1, 0x10,
	0x7a, 0xca, 0x18, 0xe3, 0xf4, 0x87, 0x74, 0x4d, 0x03, 0xd7, 0x94, 0x94, 0x71, 0xb2, 0x2e, 0xc1,
	0x01, 0xb4, 0x74, 0x5c, 0xf6, 0x34, 0x66, 0x55, 0xa9, 0x55, 0x57, 0xfa, 0x83, 0xe0, 0xd9, 0x27,
	0x21, 0x23, 0x2a, 0x46, 0x32, 0x49, 0xe2, 0x6d, 0x47, 0xd9, 0x28, 0x29, 0x24, 0x5b, 0x4c, 0xf8,
	0xb2, 0x94, 0x74, 0x6e, 0x15, 0xa6, 0x5d, 0x87, 0xf9, 0x06, 0x4f, 0xeb, 0x2c, 0xdb, 0x4c, 0x7f,
	0xff, 0x56, 0x15, 0xbc, 0x28, 0xda, 0x13, 0x29, 0x44, 0x44, 0xd9, 0xa2, 0xc9, 0x61, 0xef, 0xd9,
	0xef, 0xf7, 0x72, 0xbd, 0x6b, 0xcd, 0x66, 0x87, 0xfa, 0x87, 0xa0, 0x3d, 0x95, 0x6c, 0x81, 0x0f,
	0xa0, 0x9b, 0xa9, 0x38, 0xa1, 0x6a, 0x39, 0xb1, 0x1d, 0x7b, 0x64, 0xe5, 0x57, 0x72, 0x5f, 0xdd,
	0xf9, 0x95, 0x8f, 0x9f, 0x83, 0xa7, 0x69, 0x24, 0xb8, 0x23, 0x2f, 0x1c, 0x73, 0xe2, 0x9a, 0x6a,
	0x1a, 0xd1, 0x9c, 0xbb, 0x5b, 0x5a, 0xf9, 0xf8, 0x35, 0x00, 0x93, 0x69, 0xca, 0x99, 0x8e, 0x65,
	0x1a, 0x7a, 0x36, 0x5b, 0x89, 0x0c, 0xfe, 0x22, 0xd8, 0x27, 0xfc, 0x67, 0x9c, 0x6b, 0xae, 0x1a,
	0x5b, 0xf1, 0x1b, 0xf0, 0xcc, 0x03, 0xca, 0xc3, 0x56, 0xbf, 0x55, 0x39, 0x6a, 0x46, 0x27, 0x45,
	0xe6, 0x81, 0x87, 0xf5, 0x1b, 0xc1, 0x93, 0x35, 0xd1, 0x36, 0x17, 0x80, 0xa1, 0x6d, 0x44, 0x2c,
	0x51, 0x97, 0x58, 0xdb, 0xc6, 0x0c, 0x65, 0xb1, 0x38, 0x6b, 0x3f, 0xc0, 0xf0, 0xdf, 0x32, 0x64,
	0x52, 0x35, 0xf7, 0x8f, 0x6d, 0x02, 0xf8, 0x00, 0x9d, 0x5c, 0x53, 0x7d, 0x9b, 0x5b, 0xfd, 0xbd,
	0xe3, 0x57, 0xeb, 0x45, 0x51, 0x71, 0xa5, 0x68, 0x9a, 0x53, 0x7b, 0x4b, 0x97, 0xb6, 0x88, 0xb8,
	0xe2, 0x2a, 0xb7, 0x57, 0xe7, 0x9e, 0x83, 0x5f, 0x62, 0x37, 0xfa, 0x72, 0xdf, 0x9e, 0xc0, 0xcb,
	0xcd, 0x50, 0x18, 0xa0, 0xf3, 0xe5, 0x62, 0x72, 0x31, 0x9b, 0x07, 0x8f, 0xf0, 0x2e, 0x74, 0x47,
	0xb3, 0xf3, 0xf3, 0xf1, 0xd5, 0xd9, 0x69, 0x80, 0xf0, 0x1e, 0x00, 0x99, 0x4d, 0xa7, 0x27, 0x1f,
	0x47, 0x93, 0xb3, 0xd3, 0x60, 0x27, 0xea, 0x58, 0xe5, 0xf7, 0x77, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0x7d, 0xac, 0x69, 0xaf, 0x05, 0x00, 0x00,
}
